# Generated by Django 2.2.3 on 2019-07-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='案例编号')),
                ('casename', models.CharField(max_length=30, verbose_name='测试用例名称')),
                ('frontsql', models.CharField(blank=True, max_length=200, verbose_name='前置SQL')),
                ('apipath', models.CharField(max_length=50, verbose_name='接口路径')),
                ('requestmethod', models.CharField(max_length=20, verbose_name='请求方法')),
                ('requestdata', models.CharField(max_length=200, verbose_name='接口请求数据')),
                ('httpcodecheck', models.CharField(blank=True, max_length=20, verbose_name='HTTPcode检查点')),
                ('responsecode', models.CharField(blank=True, max_length=20, verbose_name='实际返回码')),
                ('result', models.CharField(choices=[('pass', '通过'), ('wrong', '不通过')], max_length=5, verbose_name='比对结果')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
            },
        ),
    ]
